In [2]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

from xgboost import XGBRegressor

connection_string = (
    "mssql+pyodbc://@localhost/mlb?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

engine = create_engine(connection_string)

In [5]:
query = """
select * from mlb.dbo.fact_hitter_pitcher_matchup_model_features
"""

df = pd.read_sql(query, engine)

print(df.shape)
df.head()

(24609, 448)

,gamePk,game_date,season,hitter_id,hitter_name,hitter_position,hitter_team_id,hitter_team_name,pitcher_id,pitcher_name,...,pitcher_avg_chase_rate_last_10,pitcher_avg_zone_rate_last_10,pitcher_avg_velocity_last_10,pitcher_avg_spin_rate_last_10,pitcher_avg_sl_whiff_rate_last_10,pitcher_avg_ff_whiff_rate_last_10,pitcher_prev_whiff_rate,pitcher_prev_csw_rate,pitcher_prev_chase_rate,pitcher_strikeOuts
0,778032,2025-05-06,2025,672695,Geraldo Perdomo,SS,109,Arizona Diamondbacks,656849,David Peterson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
1,777013,2025-07-25,2025,666181,Will Benson,LF,113,Cincinnati Reds,641793,Zack Littell,...,0.282231,0.534879,87.684055,1827.276940,0.078336,0.122787,0.112360,0.235955,0.306122,2
2,776712,2025-08-16,2025,672580,Maikel Garcia,3B,118,Kansas City Royals,680732,Sean Burke,...,0.320924,0.493231,88.397858,2492.036148,0.124928,0.119645,0.102273,0.306818,0.324324,3
3,776152,2025-09-27,2025,669369,Bryce Johnson,CF,135,San Diego Padres,694851,Andrew Hoffmann,...,0.263626,0.448639,90.804374,1635.216126,0.230159,0.117464,0.090909,0.181818,0.181818,0
4,777731,2025-05-28,2025,671289,Tyler Freeman,RF,115,Colorado Rockies,571510,Matthew Boyd,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8

In [7]:
# How many strikeouts the pitcher gets in THIS game
print(df.columns.tolist())

df_model = df.copy()

['gamePk', 'game_date', 'season', 'hitter_id', 'hitter_name', 'hitter_position', 'hitter_team_id', 'hitter_team_name', 'pitcher_id', 'pitcher_name', 'pitcher_team_id', 'pitcher_team_name', 'pitcher_throws', 'hitter_stand', 'hitter_strikeOuts', 'pitches_seen_vs_pitcher', 'swings_vs_pitcher', 'whiffs_vs_pitcher', 'called_strikes_vs_pitcher', 'matchup_whiff_rate', 'matchup_called_strike_rate', 'matchup_csw_rate', 'hitter_days_since_last_game', 'hitter_avg_k_last_3', 'hitter_avg_pa_last_3', 'hitter_avg_ab_last_3', 'hitter_avg_hits_last_3', 'hitter_avg_hr_last_3', 'hitter_avg_bb_last_3', 'hitter_avg_pitches_last_3', 'hitter_avg_tb_last_3', 'hitter_avg_rbi_last_3', 'hitter_avg_lob_last_3', 'hitter_avg_obp_last_3', 'hitter_avg_slg_last_3', 'hitter_avg_ops_last_3', 'hitter_avg_babip_last_3', 'hitter_avg_batting_avg_last_3', 'hitter_avg_hbp_last_3', 'hitter_avg_sf_last_3', 'hitter_avg_sbunts_last_3', 'hitter_avg_stolen_bases_last_3', 'hitter_avg_caught_stealing_last_3', 'hitter_avg_k_rate_last_3', 'hitter_avg_walk_rate_last_3', 'hitter_avg_hit_rate_last_3', 'hitter_avg_tb_rate_last_3', 'hitter_avg_hr_rate_last_3', 'hitter_sum_pa_last_3', 'hitter_sum_ab_last_3', 'hitter_pct_1plus_k_last_3', 'hitter_pct_2plus_k_last_3', 'hitter_wavg_k_last_3', 'hitter_wavg_pa_last_3', 'hitter_wavg_ab_last_3', 'hitter_wavg_hits_last_3', 'hitter_wavg_hr_last_3', 'hitter_wavg_bb_last_3', 'hitter_wavg_pitches_last_3', 'hitter_wavg_tb_last_3', 'hitter_wavg_rbi_last_3', 'hitter_wavg_lob_last_3', 'hitter_wavg_obp_last_3', 'hitter_wavg_slg_last_3', 'hitter_wavg_ops_last_3', 'hitter_wavg_babip_last_3', 'hitter_wavg_batting_avg_last_3', 'hitter_wavg_hbp_last_3', 'hitter_wavg_sf_last_3', 'hitter_wavg_sbunts_last_3', 'hitter_wavg_stolen_bases_last_3', 'hitter_wavg_caught_stealing_last_3', 'hitter_wavg_k_rate_last_3', 'hitter_wavg_walk_rate_last_3', 'hitter_wavg_hit_rate_last_3', 'hitter_wavg_tb_rate_last_3', 'hitter_wavg_hr_rate_last_3', 'hitter_avg_k_last_5', 'hitter_avg_pa_last_5', 'hitter_avg_ab_last_5', 'hitter_avg_hits_last_5', 'hitter_avg_hr_last_5', 'hitter_avg_bb_last_5', 'hitter_avg_pitches_last_5', 'hitter_avg_tb_last_5', 'hitter_avg_rbi_last_5', 'hitter_avg_lob_last_5', 'hitter_avg_obp_last_5', 'hitter_avg_slg_last_5', 'hitter_avg_ops_last_5', 'hitter_avg_babip_last_5', 'hitter_avg_batting_avg_last_5', 'hitter_avg_hbp_last_5', 'hitter_avg_sf_last_5', 'hitter_avg_sbunts_last_5', 'hitter_avg_stolen_bases_last_5', 'hitter_avg_caught_stealing_last_5', 'hitter_avg_k_rate_last_5', 'hitter_avg_walk_rate_last_5', 'hitter_avg_hit_rate_last_5', 'hitter_avg_tb_rate_last_5', 'hitter_avg_hr_rate_last_5', 'hitter_sum_pa_last_5', 'hitter_sum_ab_last_5', 'hitter_pct_1plus_k_last_5', 'hitter_pct_2plus_k_last_5', 'hitter_wavg_k_last_5', 'hitter_wavg_pa_last_5', 'hitter_wavg_ab_last_5', 'hitter_wavg_hits_last_5', 'hitter_wavg_hr_last_5', 'hitter_wavg_bb_last_5', 'hitter_wavg_pitches_last_5', 'hitter_wavg_tb_last_5', 'hitter_wavg_rbi_last_5', 'hitter_wavg_lob_last_5', 'hitter_wavg_obp_last_5', 'hitter_wavg_slg_last_5', 'hitter_wavg_ops_last_5', 'hitter_wavg_babip_last_5', 'hitter_wavg_batting_avg_last_5', 'hitter_wavg_hbp_last_5', 'hitter_wavg_sf_last_5', 'hitter_wavg_sbunts_last_5', 'hitter_wavg_stolen_bases_last_5', 'hitter_wavg_caught_stealing_last_5', 'hitter_wavg_k_rate_last_5', 'hitter_wavg_walk_rate_last_5', 'hitter_wavg_hit_rate_last_5', 'hitter_wavg_tb_rate_last_5', 'hitter_wavg_hr_rate_last_5', 'hitter_avg_k_last_10', 'hitter_avg_pa_last_10', 'hitter_avg_ab_last_10', 'hitter_avg_hits_last_10', 'hitter_avg_hr_last_10', 'hitter_avg_bb_last_10', 'hitter_avg_pitches_last_10', 'hitter_avg_tb_last_10', 'hitter_avg_rbi_last_10', 'hitter_avg_lob_last_10', 'hitter_avg_obp_last_10', 'hitter_avg_slg_last_10', 'hitter_avg_ops_last_10', 'hitter_avg_babip_last_10', 'hitter_avg_batting_avg_last_10', 'hitter_avg_hbp_last_10', 'hitter_avg_sf_last_10', 'hitter_avg_sbunts_last_10', 'hitter_avg_stolen_bases_last_10', 'hitter_avg_caught_stealing_last_10', 'hitter_avg_k_rate_last_10', 'hitter_avg_walk_rate_last_10', 'hitter_avg_hit_rate_last_10', 'hitter_avg_tb_rate_last_10', 'hitter_avg_hr_rate_last_10', 'hitter_sum_pa_last_10', 'hitter_sum_ab_last_10', 'hitter_pct_1plus_k_last_10', 'hitter_pct_2plus_k_last_10', 'hitter_wavg_k_last_10', 'hitter_wavg_pa_last_10', 'hitter_wavg_ab_last_10', 'hitter_wavg_hits_last_10', 'hitter_wavg_hr_last_10', 'hitter_wavg_bb_last_10', 'hitter_wavg_pitches_last_10', 'hitter_wavg_tb_last_10', 'hitter_wavg_rbi_last_10', 'hitter_wavg_lob_last_10', 'hitter_wavg_obp_last_10', 'hitter_wavg_slg_last_10', 'hitter_wavg_ops_last_10', 'hitter_wavg_babip_last_10', 'hitter_wavg_batting_avg_last_10', 'hitter_wavg_hbp_last_10', 'hitter_wavg_sf_last_10', 'hitter_wavg_sbunts_last_10', 'hitter_wavg_stolen_bases_last_10', 'hitter_wavg_caught_stealing_last_10', 'hitter_wavg_k_rate_last_10', 'hitter_wavg_walk_rate_last_10', 'hitter_wavg_hit_rate_last_10', 'hitter_wavg_tb_rate_last_10', 'hitter_wavg_hr_rate_last_10', 'hitter_prev_k', 'hitter_prev_pa', 'hitter_prev_ab', 'hitter_prev_hits', 'hitter_prev_hr', 'hitter_prev_bb', 'hitter_prev_pitches', 'hitter_prev_ops', 'hitter_prev_k_rate', 'hitter_avg_sc_pitches_seen_last_3', 'hitter_avg_whiff_rate_last_3', 'hitter_avg_contact_rate_last_3', 'hitter_avg_swing_rate_last_3', 'hitter_avg_chase_rate_last_3', 'hitter_avg_zone_swing_rate_last_3', 'hitter_avg_zone_rate_last_3', 'hitter_avg_called_strike_rate_last_3', 'hitter_avg_csw_against_rate_last_3', 'hitter_avg_two_strike_whiff_rate_last_3', 'hitter_avg_whiff_rate_0_2_last_3', 'hitter_avg_whiff_rate_1_2_last_3', 'hitter_avg_whiff_rate_2_2_last_3', 'hitter_avg_exit_velocity_last_3', 'hitter_avg_max_exit_velocity_last_3', 'hitter_avg_launch_angle_last_3', 'hitter_avg_hit_distance_last_3', 'hitter_avg_xba_last_3', 'hitter_avg_xwoba_last_3', 'hitter_avg_woba_value_last_3', 'hitter_avg_babip_value_last_3', 'hitter_avg_iso_value_last_3', 'hitter_avg_bat_speed_last_3', 'hitter_avg_swing_length_last_3', 'hitter_avg_pitch_velocity_seen_last_3', 'hitter_avg_pitch_spin_seen_last_3', 'hitter_avg_pitch_extension_seen_last_3', 'hitter_avg_horz_movement_seen_last_3', 'hitter_avg_vert_movement_seen_last_3', 'hitter_avg_plate_x_seen_last_3', 'hitter_avg_plate_z_seen_last_3', 'hitter_avg_ff_seen_pct_last_3', 'hitter_avg_si_seen_pct_last_3', 'hitter_avg_fc_seen_pct_last_3', 'hitter_avg_sl_seen_pct_last_3', 'hitter_avg_cu_seen_pct_last_3', 'hitter_avg_ch_seen_pct_last_3', 'hitter_avg_fs_seen_pct_last_3', 'hitter_avg_whiff_rate_vs_rhp_last_3', 'hitter_avg_whiff_rate_vs_lhp_last_3', 'hitter_wavg_sc_pitches_seen_last_3', 'hitter_wavg_whiff_rate_last_3', 'hitter_wavg_contact_rate_last_3', 'hitter_wavg_swing_rate_last_3', 'hitter_wavg_chase_rate_last_3', 'hitter_wavg_zone_swing_rate_last_3', 'hitter_wavg_zone_rate_last_3', 'hitter_wavg_called_strike_rate_last_3', 'hitter_wavg_csw_against_rate_last_3', 'hitter_wavg_two_strike_whiff_rate_last_3', 'hitter_wavg_whiff_rate_0_2_last_3', 'hitter_wavg_whiff_rate_1_2_last_3', 'hitter_wavg_whiff_rate_2_2_last_3', 'hitter_wavg_exit_velocity_last_3', 'hitter_wavg_max_exit_velocity_last_3', 'hitter_wavg_launch_angle_last_3', 'hitter_wavg_hit_distance_last_3', 'hitter_wavg_xba_last_3', 'hitter_wavg_xwoba_last_3', 'hitter_wavg_woba_value_last_3', 'hitter_wavg_babip_value_last_3', 'hitter_wavg_iso_value_last_3', 'hitter_wavg_bat_speed_last_3', 'hitter_wavg_swing_length_last_3', 'hitter_wavg_pitch_velocity_seen_last_3', 'hitter_wavg_pitch_spin_seen_last_3', 'hitter_wavg_pitch_extension_seen_last_3', 'hitter_wavg_horz_movement_seen_last_3', 'hitter_wavg_vert_movement_seen_last_3', 'hitter_wavg_plate_x_seen_last_3', 'hitter_wavg_plate_z_seen_last_3', 'hitter_wavg_ff_seen_pct_last_3', 'hitter_wavg_si_seen_pct_last_3', 'hitter_wavg_fc_seen_pct_last_3', 'hitter_wavg_sl_seen_pct_last_3', 'hitter_wavg_cu_seen_pct_last_3', 'hitter_wavg_ch_seen_pct_last_3', 'hitter_wavg_fs_seen_pct_last_3', 'hitter_wavg_whiff_rate_vs_rhp_last_3', 'hitter_wavg_whiff_rate_vs_lhp_last_3', 'hitter_avg_sc_pitches_seen_last_5', 'hitter_avg_whiff_rate_last_5', 'hitter_avg_contact_rate_last_5', 'hitter_avg_swing_rate_last_5', 'hitter_avg_chase_rate_last_5', 'hitter_avg_zone_swing_rate_last_5', 'hitter_avg_zone_rate_last_5', 'hitter_avg_called_strike_rate_last_5', 'hitter_avg_csw_against_rate_last_5', 'hitter_avg_two_strike_whiff_rate_last_5', 'hitter_avg_exit_velocity_last_5', 'hitter_avg_xwoba_last_5', 'hitter_avg_bat_speed_last_5', 'hitter_avg_whiff_rate_vs_rhp_last_5', 'hitter_avg_whiff_rate_vs_lhp_last_5', 'hitter_wavg_sc_pitches_seen_last_5', 'hitter_wavg_whiff_rate_last_5', 'hitter_wavg_contact_rate_last_5', 'hitter_wavg_swing_rate_last_5', 'hitter_wavg_chase_rate_last_5', 'hitter_wavg_zone_swing_rate_last_5', 'hitter_wavg_zone_rate_last_5', 'hitter_wavg_called_strike_rate_last_5', 'hitter_wavg_csw_against_rate_last_5', 'hitter_wavg_two_strike_whiff_rate_last_5', 'hitter_wavg_exit_velocity_last_5', 'hitter_wavg_xwoba_last_5', 'hitter_wavg_bat_speed_last_5', 'hitter_wavg_whiff_rate_vs_rhp_last_5', 'hitter_wavg_whiff_rate_vs_lhp_last_5', 'hitter_avg_sc_pitches_seen_last_10', 'hitter_avg_whiff_rate_last_10', 'hitter_avg_contact_rate_last_10', 'hitter_avg_swing_rate_last_10', 'hitter_avg_chase_rate_last_10', 'hitter_avg_zone_swing_rate_last_10', 'hitter_avg_zone_rate_last_10', 'hitter_avg_called_strike_rate_last_10', 'hitter_avg_csw_against_rate_last_10', 'hitter_avg_two_strike_whiff_rate_last_10', 'hitter_avg_exit_velocity_last_10', 'hitter_avg_xwoba_last_10', 'hitter_avg_bat_speed_last_10', 'hitter_avg_whiff_rate_vs_rhp_last_10', 'hitter_avg_whiff_rate_vs_lhp_last_10', 'hitter_wavg_sc_pitches_seen_last_10', 'hitter_wavg_whiff_rate_last_10', 'hitter_wavg_contact_rate_last_10', 'hitter_wavg_swing_rate_last_10', 'hitter_wavg_chase_rate_last_10', 'hitter_wavg_zone_swing_rate_last_10', 'hitter_wavg_zone_rate_last_10', 'hitter_wavg_called_strike_rate_last_10', 'hitter_wavg_csw_against_rate_last_10', 'hitter_wavg_two_strike_whiff_rate_last_10', 'hitter_wavg_exit_velocity_last_10', 'hitter_wavg_xwoba_last_10', 'hitter_wavg_bat_speed_last_10', 'hitter_wavg_whiff_rate_vs_rhp_last_10', 'hitter_wavg_whiff_rate_vs_lhp_last_10', 'hitter_prev_whiff_rate', 'hitter_prev_contact_rate', 'hitter_prev_chase_rate', 'hitter_prev_exit_velocity', 'hitter_prev_xwoba', 'hitter_prev_bat_speed', 'pitcher_gamesStarted', 'pitcher_days_since_last_appearance', 'pitcher_avg_games_started_last_3', 'pitcher_avg_ip_last_3', 'pitcher_avg_bf_last_3', 'pitcher_avg_pitches_last_3', 'pitcher_avg_outs_last_3', 'pitcher_avg_k_last_3', 'pitcher_avg_k9_last_3', 'pitcher_avg_era_last_3', 'pitcher_avg_whip_last_3', 'pitcher_avg_bb_last_3', 'pitcher_avg_hr_last_3', 'pitcher_avg_hits_last_3', 'pitcher_avg_strike_pct_last_3', 'pitcher_avg_kbb_last_3', 'pitcher_sum_pitches_last_3', 'pitcher_sum_bf_last_3', 'pitcher_pct_5plus_ip_last_3', 'pitcher_pct_6plus_ip_last_3', 'pitcher_avg_games_started_last_5', 'pitcher_avg_ip_last_5', 'pitcher_avg_bf_last_5', 'pitcher_avg_pitches_last_5', 'pitcher_avg_outs_last_5', 'pitcher_avg_k_last_5', 'pitcher_avg_k9_last_5', 'pitcher_avg_era_last_5', 'pitcher_avg_whip_last_5', 'pitcher_avg_bb_last_5', 'pitcher_avg_hr_last_5', 'pitcher_avg_hits_last_5', 'pitcher_avg_strike_pct_last_5', 'pitcher_avg_kbb_last_5', 'pitcher_sum_pitches_last_5', 'pitcher_sum_bf_last_5', 'pitcher_pct_5plus_ip_last_5', 'pitcher_pct_6plus_ip_last_5', 'pitcher_avg_games_started_last_10', 'pitcher_avg_ip_last_10', 'pitcher_avg_bf_last_10', 'pitcher_avg_pitches_last_10', 'pitcher_avg_outs_last_10', 'pitcher_avg_k_last_10', 'pitcher_avg_k9_last_10', 'pitcher_avg_era_last_10', 'pitcher_avg_whip_last_10', 'pitcher_avg_bb_last_10', 'pitcher_avg_hr_last_10', 'pitcher_avg_hits_last_10', 'pitcher_avg_strike_pct_last_10', 'pitcher_avg_kbb_last_10', 'pitcher_sum_pitches_last_10', 'pitcher_sum_bf_last_10', 'pitcher_pct_5plus_ip_last_10', 'pitcher_pct_6plus_ip_last_10', 'pitcher_prev_k', 'pitcher_prev_ip', 'pitcher_prev_bf', 'pitcher_prev_pitches', 'pitcher_prev_k9', 'pitcher_avg_whiff_rate_last_3', 'pitcher_avg_csw_rate_last_3', 'pitcher_avg_putaway_rate_last_3', 'pitcher_avg_swing_rate_last_3', 'pitcher_avg_chase_rate_last_3', 'pitcher_avg_zone_rate_last_3', 'pitcher_avg_whiff_rate_0_2_last_3', 'pitcher_avg_whiff_rate_1_2_last_3', 'pitcher_avg_whiff_rate_2_2_last_3', 'pitcher_avg_velocity_last_3', 'pitcher_avg_spin_rate_last_3', 'pitcher_avg_extension_last_3', 'pitcher_avg_plate_x_last_3', 'pitcher_avg_plate_z_last_3', 'pitcher_avg_ff_pct_last_3', 'pitcher_avg_si_pct_last_3', 'pitcher_avg_fc_pct_last_3', 'pitcher_avg_sl_pct_last_3', 'pitcher_avg_cu_pct_last_3', 'pitcher_avg_ch_pct_last_3', 'pitcher_avg_fs_pct_last_3', 'pitcher_avg_sl_whiff_rate_last_3', 'pitcher_avg_ff_whiff_rate_last_3', 'pitcher_avg_whiff_rate_last_5', 'pitcher_avg_csw_rate_last_5', 'pitcher_avg_putaway_rate_last_5', 'pitcher_avg_swing_rate_last_5', 'pitcher_avg_chase_rate_last_5', 'pitcher_avg_zone_rate_last_5', 'pitcher_avg_velocity_last_5', 'pitcher_avg_spin_rate_last_5', 'pitcher_avg_sl_whiff_rate_last_5', 'pitcher_avg_ff_whiff_rate_last_5', 'pitcher_avg_whiff_rate_last_10', 'pitcher_avg_csw_rate_last_10', 'pitcher_avg_putaway_rate_last_10', 'pitcher_avg_swing_rate_last_10', 'pitcher_avg_chase_rate_last_10', 'pitcher_avg_zone_rate_last_10', 'pitcher_avg_velocity_last_10', 'pitcher_avg_spin_rate_last_10', 'pitcher_avg_sl_whiff_rate_last_10', 'pitcher_avg_ff_whiff_rate_last_10', 'pitcher_prev_whiff_rate', 'pitcher_prev_csw_rate', 'pitcher_prev_chase_rate', 'pitcher_strikeOuts']

In [16]:
target = "pitcher_strikeOuts"

drop_cols = [
    "gamePk",
    "game_date",
    "hitter_name",
    "pitcher_name",
    "hitter_position",
    "hitter_team_name",
    "pitcher_team_name"
]

X = df.drop(columns=drop_cols + [target])
y = df[target]

print(x.shape)
print(y.shape)
print(X.dtypes[X.dtypes == "object"])

(24609, 443)
(24609,)
Series([], dtype: object)

In [17]:
# Handle categorical columns
# pitcher_thros (L/R) & hitter_stand (L/R)
# XGBoost cannot handle strings
# This will make pitcher_throws_R = 1 -> right handed
# pitcher_thros_R = 0 -> left handed

X = pd.get_dummies(X, columns=["pitcher_throws", "hitter_stand"], drop_first=True)

In [18]:
# clean nulls and fill it with 0
X = X.fillna(0)

In [19]:
# important - train 80% and test 20% (unseen data)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size = 0.2,
    random_state = 42
)

print(X_train.shape, X_test.shape)

(19687, 440) (4922, 440)

In [ ]:
# Train XGBoost model - make sure there is no string in any of the columns
model = XGBRegressor(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [22]:
# Predicit 
y_pred = model.predict(X_test)

print(y_pred[:10])

[6.5369325 3.991674  6.3926363 5.0490212 8.604009  4.33734   2.823751
 3.0149028 2.7390902 4.043201 ]

In [ ]:
# Metrics - measure accuracy 
# MAE - average error  0.8 = VERY GOOD, 1.2 = good, 1.5+ needs improvement
# RMSE - penalizes big misses, should be slightly higher than MAE

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 1.2418639659881592
RMSE: 1.5924689436299162

In [30]:
# Results table - 1 row = hitter vs pitcher

results = df.loc[X_test.index].copy()

results["predicted_strikeouts"] = y_pred

results[[
    "pitcher_name",
    "hitter_name",
    "pitcher_team_name",
    "pitcher_strikeOuts",
    "predicted_strikeouts",
]].head(20)

,pitcher_name,hitter_name,pitcher_team_name,pitcher_strikeOuts,predicted_strikeouts
3733,Kyle Bradish,Jarren Duran,Baltimore Orioles,10,6.536932
11502,Colin Rea,Ben Williamson,Chicago Cubs,2,3.991674
6423,Jesús Luzardo,Pedro Pagés,Philadelphia Phillies,6,6.392636
15983,Cade Povich,Ryan O'Hearn,Baltimore Orioles,3,5.049021
23613,Dylan Cease,Will Smith,Toronto Blue Jays,9,8.604009
21992,Taijuan Walker,Casey Schmitt,Philadelphia Phillies,3,4.337340
5843,Aaron Nola,CJ Abrams,Philadelphia Phillies,4,2.823751
2168,Antonio Senzatela,Luis García Jr.,Colorado Rockies,0,3.014903
12110,Ranger Suarez,Xander Bogaerts,Boston Red Sox,2,2.739090
1103,Andrew Abbott,Alec Burleson,Cincinnati Reds,3,4.043201
22654,Walker Buehler,Jazz Chisholm Jr.,San Diego Padres,2,4.039827
1457,Dustin May,Wilyer Abreu,St. Louis Cardinals,5,4.543074
9161,Andrew Abbott,Thomas Saggese,Cincinnati Reds,7,5.964141
17723,Brayan Bello,Aaron Judge,Boston Red Sox,5,4.307099
4202,Paul Skenes,Riley Greene,Pittsburgh Pirates,6,8.161584
1765,Sean Burke,Spencer Torkelson,Chicago White Sox,5,5.025321
20182,Kevin Gausman,Jake Burger,Toronto Blue Jays,6,5.428417
7191,Framber Valdez,Marcus Semien,Detroit Tigers,10,7.820565
3752,Michael McGreevy,Jordan Beck,St. Louis Cardinals,2,3.588749
2744,Chase Dollander,Corbin Carroll,Colorado Rockies,6,4.706662

In [36]:
# Aggregate predictions - multiple hitters per pitch

pitcher_preds = results.groupby(
    ["gamePk", "pitcher_name","pitcher_team_name"]
).agg(
    actual_K=("pitcher_strikeOuts", "first"),
    predicted_K=("predicted_strikeouts", "mean")
).reset_index()

pitcher_preds.head(20)

,gamePk,pitcher_name,pitcher_team_name,actual_K,predicted_K
0,776136,Brandon Pfaadt,Arizona Diamondbacks,5,4.223785
1,776137,Antonio Senzatela,Colorado Rockies,0,1.561338
2,776137,Juan Mejia,Colorado Rockies,1,1.363863
3,776137,Logan Webb,San Francisco Giants,8,7.546691
4,776138,Cole Ragans,Kansas City Royals,8,7.286646
5,776140,Rico Garcia,Baltimore Orioles,2,0.743285
6,776141,Simeon Woods Richardson,Minnesota Twins,9,5.464324
7,776143,Brad Lord,Washington Nationals,4,4.894092
8,776143,Shane Smith,Chicago White Sox,8,6.596539
9,776144,Aaron Ashby,Milwaukee Brewers,2,1.716247
10,776144,Brady Singer,Cincinnati Reds,5,5.287321
11,776144,Freddy Peralta,New York Mets,3,5.260373
12,776144,Scott Barlow,Athletics,1,1.444921
13,776145,Bryan Baker,Tampa Bay Rays,3,0.968218
14,776145,Ian Seymour,Tampa Bay Rays,7,5.661412
15,776145,Kevin Kelly,Tampa Bay Rays,1,0.652787
16,776148,Edward Cabrera,Chicago Cubs,7,6.370071
17,776148,Edwin Díaz,Los Angeles Dodgers,1,1.655675
18,776148,Tyler Phillips,Miami Marlins,0,0.624716
19,776150,Logan Gilbert,Seattle Mariners,5,5.513192

In [37]:
# add betting decision 
pitcher_preds["line"] = 5.5  # example (later from sportsbook)

pitcher_preds["edge"] = pitcher_preds["predicted_K"] - pitcher_preds["line"]

pitcher_preds["bet"] = pitcher_preds["edge"].apply(
    lambda x: "OVER" if x > 0 else "UNDER"
)

pitcher_preds.head(20)

,gamePk,pitcher_name,pitcher_team_name,actual_K,predicted_K,line,edge,bet
0,776136,Brandon Pfaadt,Arizona Diamondbacks,5,4.223785,5.5,-1.276215,UNDER
1,776137,Antonio Senzatela,Colorado Rockies,0,1.561338,5.5,-3.938662,UNDER
2,776137,Juan Mejia,Colorado Rockies,1,1.363863,5.5,-4.136137,UNDER
3,776137,Logan Webb,San Francisco Giants,8,7.546691,5.5,2.046691,OVER
4,776138,Cole Ragans,Kansas City Royals,8,7.286646,5.5,1.786646,OVER
5,776140,Rico Garcia,Baltimore Orioles,2,0.743285,5.5,-4.756715,UNDER
6,776141,Simeon Woods Richardson,Minnesota Twins,9,5.464324,5.5,-0.035676,UNDER
7,776143,Brad Lord,Washington Nationals,4,4.894092,5.5,-0.605908,UNDER
8,776143,Shane Smith,Chicago White Sox,8,6.596539,5.5,1.096539,OVER
9,776144,Aaron Ashby,Milwaukee Brewers,2,1.716247,5.5,-3.783753,UNDER
10,776144,Brady Singer,Cincinnati Reds,5,5.287321,5.5,-0.212679,UNDER
11,776144,Freddy Peralta,New York Mets,3,5.260373,5.5,-0.239627,UNDER
12,776144,Scott Barlow,Athletics,1,1.444921,5.5,-4.055079,UNDER
13,776145,Bryan Baker,Tampa Bay Rays,3,0.968218,5.5,-4.531782,UNDER
14,776145,Ian Seymour,Tampa Bay Rays,7,5.661412,5.5,0.161412,OVER
15,776145,Kevin Kelly,Tampa Bay Rays,1,0.652787,5.5,-4.847213,UNDER
16,776148,Edward Cabrera,Chicago Cubs,7,6.370071,5.5,0.870071,OVER
17,776148,Edwin Díaz,Los Angeles Dodgers,1,1.655675,5.5,-3.844325,UNDER
18,776148,Tyler Phillips,Miami Marlins,0,0.624716,5.5,-4.875284,UNDER
19,776150,Logan Gilbert,Seattle Mariners,5,5.513192,5.5,0.013192,OVER

In [38]:
import pandas as pd

feature_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
}).sort_values("importance", ascending=False)

feature_importance.head(20)

                            feature  importance
331            pitcher_gamesStarted    0.217931
374           pitcher_avg_k_last_10    0.034023
8                 whiffs_vs_pitcher    0.019425
356            pitcher_avg_k_last_5    0.017574
5                 hitter_strikeOuts    0.017028
425  pitcher_avg_whiff_rate_last_10    0.014985
12                 matchup_csw_rate    0.010233
415   pitcher_avg_whiff_rate_last_5    0.008949
10               matchup_whiff_rate    0.008941
389                 pitcher_prev_bf    0.008517
335           pitcher_avg_bf_last_3    0.007757
421     pitcher_avg_velocity_last_5    0.007284
373        pitcher_avg_outs_last_10    0.007008
352           pitcher_avg_ip_last_5    0.006700
426    pitcher_avg_csw_rate_last_10    0.006228
377        pitcher_avg_whip_last_10    0.006009
354      pitcher_avg_pitches_last_5    0.005963
431    pitcher_avg_velocity_last_10    0.005902
409       pitcher_avg_sl_pct_last_3    0.005848
438                pitcher_throws_R    0.005821

In [39]:
feature_importance.head(20)

                            feature  importance
331            pitcher_gamesStarted    0.217931
374           pitcher_avg_k_last_10    0.034023
8                 whiffs_vs_pitcher    0.019425
356            pitcher_avg_k_last_5    0.017574
5                 hitter_strikeOuts    0.017028
425  pitcher_avg_whiff_rate_last_10    0.014985
12                 matchup_csw_rate    0.010233
415   pitcher_avg_whiff_rate_last_5    0.008949
10               matchup_whiff_rate    0.008941
389                 pitcher_prev_bf    0.008517
335           pitcher_avg_bf_last_3    0.007757
421     pitcher_avg_velocity_last_5    0.007284
373        pitcher_avg_outs_last_10    0.007008
352           pitcher_avg_ip_last_5    0.006700
426    pitcher_avg_csw_rate_last_10    0.006228
377        pitcher_avg_whip_last_10    0.006009
354      pitcher_avg_pitches_last_5    0.005963
431    pitcher_avg_velocity_last_10    0.005902
409       pitcher_avg_sl_pct_last_3    0.005848
438                pitcher_throws_R    0.005821